### ISSUE TITLE
TypeError: can't convert 'int' object to str implicitly

### ISSUE THREAD

**Issue by KTibow** [adafruit/Adafruit_CircuitPython_miniQR#18]
I decided to try out the `magtag.graphics.qrcode` function. However, I get the exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_magtag/graphics.py", line 86, in qrcode
  File "adafruit_portalbase/graphics.py", line 129, in qrcode
  File "adafruit_portalbase/graphics.py", line 126, in qrcode
  File "adafruit_miniqr.py", line 127, in make
  File "adafruit_miniqr.py", line 253, in _create_data
  File "adafruit_miniqr.py", line 596, in put
TypeError: can't convert 'int' object to str implicitly
```
I looked at the code, but couldn't quite understand why this is happening. Is there any way for this to be fixed?

**Comment by KTibow** [comment]
The MagTag docs weren't clear I was supposed to encode my data. I'm sending in a patch to auto-encode if the type is `str`.
